#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM artifacts.cf.saxo/docker-base/base/saxo-dotnet-sdk:5.0-alpine-ci-1.0.25 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM artifacts.cf.saxo/docker-base/base/saxo-dotnet-sdk:5.0-alpine-ci-1.0.25 AS build
WORKDIR /src
COPY ["src/orders/Orders.csproj", "src/orders/"]
RUN dotnet restore "src/orders/Orders.csproj"
COPY . .
WORKDIR "/src/src/orders"
RUN dotnet build "Orders.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Orders.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Orders.dll"]