FROM artifacts.cf.saxo/docker-base/base/saxo-dotnet-sdk:5.0-alpine-ci-1.0.20 AS build
WORKDIR /sln

# Copy project file and restore
COPY "./orders.csproj" "./src/orders/"
RUN dotnet restore ./src/orders/orders.csproj -s https://artifacts.cf.saxo/artifactory/api/nuget/ThirdPartyNuget

# Copy the actual source code
COPY "." "./src/orders"

# Build and publish the app
RUN dotnet publish "./src/orders/orders.csproj" -c Release -o /app/publish

#FINAL image
FROM artifacts.cf.saxo/docker-base/base/saxo-dotnet-sdk:5.0-alpine-ci-1.0.20
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "orders.dll"]